sudo: required
language: node_js
services:
  - docker
  - xvfb
node_js:
  - v8
  - v10
  - v12

## Missing dependency for Cypress https://github.com/cypress-io/cypress/issues/4069
addons:
  apt:
    packages:
    - libgconf-2-4

  
## Cache NPM folder and Cypress binary
## to avoid downloading Cypress again and again
cache:
  directories:
    - ~/.npm
    - ~/.cache

  override:
    # use the new "ci" command for fastest installs on CI
    - npm ci
    - npm run cy:verify

before_script:
  ## we use the '&' ampersand which tells
  ## travis to run this process in the background
  ## else it would block execution and hang travis
  - docker run -d -p 27017:27017 mongo:4.0
  - docker ps -a
  - NODE_ENV=test npm start -- --silent &

script:
  - npm run test:ci

  hf = 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
  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
  xapp-1-A06NQ2Q6B5K-6807319473558-1dae683813ad94a8de5675da3a2df8032e0db362b70d7ef29742c61df31b63a0
  AIzaSyCWk_6EJrtgAS-mLtyr3aaKwWBxgUu1D1I
